"""Create the Elasticsearch index for hybrid (BM25 + kNN) retrieval over the
AVeriTeC dev knowledge store.

Schema is chunk-level, matching the real knowledge-store format confirmed
by inspecting actual downloaded files: each claim has its own knowledge
file ({claim_id}.json), one JSON object per line, shaped like
{"claim_id": ..., "type": ..., "query": ..., "url": ...,
"url2text": [sentence, sentence, ...]}. So each retrievable unit here is
one sentence/chunk from one URL, scoped to one claim.

Retrieval must always filter by claim_id first, the knowledge store is
NOT a single shared corpus across all 500 claims, it's 500 separate,
claim-scoped evidence pools.

`type` and `query` are provenance from the ORIGINAL baseline's own
multi-strategy retrieval (question_duplicate, gpt_question, NER, "gold",
etc. confirmed 14 distinct types in a sample file, including a "gold"
type marking human-verified evidence). We index these for debugging/
provenance (e.g. checking whether our own retrieval surfaces the same
documents the "gold" type marks), but our agent's own retrieval queries
must be generated by our own decomposition step, reusing these
baseline-supplied `query` values directly would be cheating off the
original baseline's retrieval work instead of demonstrating our own
sufficiency-loop agent.

Usage:
    uv run scripts/setup_es_index.py
"""

from elasticsearch import Elasticsearch

INDEX_NAME = "averitec_dev_chunks"
EMBEDDING_DIMS = 384  # matches sentence-transformers/all-MiniLM-L6-v2

MAPPING = {
    "properties": {
        "claim_id": {"type": "keyword"},  # ALWAYS filter on this first
        "url": {"type": "keyword"},
        "text": {"type": "text"},  # BM25 keyword search
        "source_type": {"type": "keyword"},  # provenance from original baseline's `type`
        "source_query": {"type": "keyword"},  # provenance from original baseline's `query`
        "embedding": {
            "type": "dense_vector",
            "dims": EMBEDDING_DIMS,
            "index": True,
            "similarity": "cosine",
        },
    }
}


def main():
    es = Elasticsearch("http://localhost:9200")

    if not es.ping():
        raise SystemExit(
            "Can't reach Elasticsearch at localhost:9200 — "
            "is `docker compose up -d` running?"
        )

    if es.indices.exists(index=INDEX_NAME):
        print(f"Index '{INDEX_NAME}' already exists, leaving as-is.")
        return

    es.indices.create(index=INDEX_NAME, mappings=MAPPING)
    print(f"Created index '{INDEX_NAME}'.")


if __name__ == "__main__":
    main()
